config/routes.rb
Museusoaresreis::Application.routes.draw do

  # Authentication
  get "/login" => "admin#login", as: "login"
  get "/logout" => "admin#logout", as: "logout"
  get "/generatePassword" => "admin#generatePassword"

  # Administrator
  resources :administrators

  # Events
  resources :events
  get "/events/:id/translate" => "events#translate", as: "translate"


  # Languages
  resources :languages
  get "/getMissingLangs" => "languages#getMissingLangs"
  get "/changeLang" => "languages#changeLang"

  # Translations
  get "/findTranslation" => "event_translations#findTranslation"
  get "/updateTranslation" => "event_translations#updateTranslation"
  resources :event_translations

  # Root
  root "media#index"

  #Media
  get "/getDates" => "media#getDates"
  get "/getEvents" => "media#getEvents"
  get "/getTranslations" => "media#getTranslations"
  get "/getImage" => "media#getImage"
  get "/getEvent" => "media#getEvent"
  get "/puzzle" => "media#puzzle"
  get "/getEventTranslation" => "media#getTranslationEvent"

end

app/views/admin/_adminActions.html.erb
<ul>

  <%
     seeAdmins = ""
     createAdmin = ""
     seeLanguages= ""
     html = "<div class='arrow-left'></div>".html_safe
     if params[:action] == "index" and params[:controller] == "administrators"
       seeAdmins = html
     elsif params[:action] == "new" and params[:controller] == "administrators"
       createAdmin = html
     elsif params[:action] == "index" and params[:controller] == "languages"
       seeLanguages = html
     end
  %>
  <li><a href="/administrators">Ver Administradores</a> <%=seeAdmins%></li>
  <li><a href="/administrators/new">Adicionar Administrador</a> <%=createAdmin%></li>
  <li><a href="/languages">Línguas</a> <%=seeLanguages%></li>
</ul>

app/views/admin/_eventsActions.html.erb
<ul>
  <%
     seeEvents = ""
     createEvents = ""
     html = "<div class='arrow-left'></div>".html_safe
     if params[:action] == "index"
       seeEvents = html
     else
       createEvents = html
     end
  %>
  <li><a href="/events">Ver eventos</a>  <%= seeEvents%></li>
  <li><a href="/events/new">Criar evento</a> <%= createEvents%></li>
</ul>

app/views/admin/_header.html.erb
<div id="header">
  <%=image_tag("logo-white.png", alt: "Museu Nacional Soares dos Reis")%>
  <% if @adminSession %>
  <div class="logout">
    <button id="logoutButton">Sair da Administração</button>
  </div>
  <div class="administrator">
    <%= @adminSession.name %>
  </div>
  <% end %>
</div>

app/views/admin/_menu.html.erb
<div class="menu">
  <%
    adminMenu = ""
    eventsMenu = ""
    if params[:controller] == "events"
        eventsMenu = "active"
    else
        adminMenu = "active"
    end
  %>
  <a href="<%= administrators_path %>"><div class="option <%= adminMenu%>">Gerir Administradores</div></a>
  <a href="<%= events_path %>"><div class="option <%= eventsMenu %>">Gerir Eventos</div></a>
</div>

app/views/admin/addAdmin.html.erb
<% content_for :title, "Adicionar Administrador" %>
<%= render "header" %>
<div class="box">
  <%= render "menu" %>
  <div class="actions">
    <%= render "adminActions" %>
  </div>
  <div class="view" id="addAdmin">

    <div class="notifications">
    </div>
    <input type="text" id="nameVal" placeholder="Nome"/><br/>
    <input type="email" id="emailVal" placeholder="Email"/><br/>
    <input type="password" id="password1Val" placeholder="Password"/><br/>
    <input type="password" id="password2Val" placeholder="Confirme a password"/><br/>

    <button class="redButton" id="addAdminButton">Adicionar Administrador</button>
  </div>
</div>

app/views/admin/addEvent.html.erb
<% content_for :title, "Criar Evento" %>
<%= render "header" %>
<div class="box">
  <%= render "menu" %>
  <div class="actions">
    <%= render "eventsActions" %>
  </div>

  <div class="view" id="addEvent">
    <div class="notifications"></div>
    <form action="addEvent" method="post" onsubmit="return validateAddEvent()">
      <input type="text" name="date" class="date" id="datepicker" placeholder="Data"/>
      <input type="text" name="local" placeholder="Localização" id="localInput" class="local"/>
      <div class="locationResults">
        <ul>
        </ul>
      </div>
      <textarea rows="10" placeholder="Inserir texto" name="text" id="text"></textarea><br/>
      Inserir Imagens
      <div class="imagesArea">
        <input type="file" name="image1" id="image1"/>
        <input type="file" name="image2" id="image2"/>
        <input type="file" name="image3" id="image3"/>
      </div>
      <button class="redButton" id="addEventButton">Adicionar Evento</button>
    </form>
  </div>

</div>

app/views/admin/forgotPassword.html.erb
<% content_for :title, "Sistema Administrativo" %>
<%= render "header" %>
<div id="content">
  <div class="notifications">
  </div>
  <div id="forgotPasswordInfo">
     <input type="text" name="email" id="emailForgot" placeholder="e-mail"/> <br/>
     <button id="generatePasswordButton">Gerar Nova Password</button></br>
     Foi lhe enviado um email com o procedimento a seguir de forma a recuperar a sua palavra chave. Por favor verifique a sua conta de email.
  </div>
</div>

app/views/admin/login.html.erb
<% content_for :title, "Sistema Administrativo" %>
<%= render "header" %>
<div id="content">
  <div id="loginForm">
    <%=image_tag("logo.png", alt: "Museu Nacional Soares dos Reis")%>
    <h2>Sistema administrativo</h2>
    <div class="notifications">
    </div>
    <input type="text" name="email" id="emailVal" placeholder="e-mail"/> <br/>
    <input type="password" name="password" id="passwordVal" placeholder="password"/> <br/>
    <button id="loginButton">Entrar</button> <br/>
    <button id="forgotPasswordButton">Esqueceu a password?</button> <br/>
  </div>
 </div>