config/routes.rb
Museusoaresreis::Application.routes.draw do

  # Authentication
  get "/login" => "admin#login", as: "login"
  get "/logout" => "admin#logout", as: "logout"
  get "/generatePassword" => "admin#generatePassword"

  # Administrator
  resources :administrators

  # Events
  resources :events
  get "/events/:id/translate" => "events#translate", as: "translate"


  # Languages
  resources :languages
  get "/getMissingLangs" => "languages#getMissingLangs"
  get "/changeLang" => "languages#changeLang"

  # Translations
  get "/findTranslation" => "event_translations#findTranslation"
  get "/updateTranslation" => "event_translations#updateTranslation"
  resources :event_translations

  # Root
  root "media#index"

  #Media
  get "/getDates" => "media#getDates"
  get "/getEvents" => "media#getEvents"
  get "/getTranslations" => "media#getTranslations"
  get "/getImage" => "media#getImage"
  get "/getEvent" => "media#getEvent"
  get "/puzzle" => "media#puzzle"
  get "/getEventTranslation" => "media#getTranslationEvent"

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :chronology
  belongs_to :map
  has_many :images, dependent: :destroy
  has_many :event_translation
  validates :title, presence:true
  #validates :content, presence:true
  #validates :chronology, presence:true
  #validates :map, presence:true
  before_save :default_values

  def default_values
    self.published = 'false' if self.published.nil?
    self.public = 'false' if self.public.nil?
  end

  # Returns all the locations within a search term
  def self.listLocations(searchTerm)
    Event.where(["local REGEXP :term", {:term => searchTerm}]).map(&:local)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_auth, :only => [:new, :create, :update, :edit, :destroy, :index, :show]
  before_action :find , :only => [:update, :destroy, :show, :edit]

  def find
    @event = Event.find(params[:id])
  end

  def new
  end

  def create
    title = params[:title]
    date = params[:date]
    content = params[:content]
    image1 = params[:image1]
    caption1 = params[:caption1]
    title_img1 = params[:title_img1]
    image2 = params[:image2]
    caption2 = params[:caption2]
    title_img2 = params[:title_img2]
    image3 = params[:image3]
    caption3 = params[:caption3]
    title_img3 = params[:title_img3]
    directory = "public/data"

    @event = Event.create(title: title, date: date, content: content)

    if(image1)
      hash = Time.new.to_formatted_s(:number) + "_" + rand(9999).to_s + File.extname(image1.original_filename)
      path = File.join(directory, hash)
      @image = @event.images.create(name: image1.original_filename, path: path, hashcode: hash, caption: caption1, title: title_img1)
      Image.uploadFile(image1,hash)
    end

    if(image2)
      hash = Time.new.to_formatted_s(:number) + "_" + rand(9999).to_s + File.extname(image2.original_filename)
      path = File.join(directory, hash)
      @image = @event.images.create(name: image2.original_filename, path: path, hashcode: hash, caption: caption2, title: title_img2)
      Image.uploadFile(image2,hash)
    end

    if(image3)
      hash = Time.new.to_formatted_s(:number) + "_" + rand(9999).to_s + File.extname(image3.original_filename)
      path = File.join(directory, hash)
      @image = @event.images.create(name: image3.original_filename, path: path, hashcode: hash, caption: caption3, title: title_img3)
      Image.uploadFile(image3,hash)
    end

    languages = Language.all
    languages.each do |language|
    	if language.code != 'pt'
    		EventTranslation.create(title:"",content:"", lang:language.code, event:@event)
    	end
    end
    redirect_to(events_path, :notice => "Evento criado com sucesso!")
  end

  def update
    title = params[:title]
    date = params[:date]
    content = params[:content]
    image1 = params[:image1]
    caption1 = params[:caption1]
    title_img1 = params[:title_img1]
    image2 = params[:image2]
    caption2 = params[:caption2]
    title_img2 = params[:title_img2]
    image3 = params[:image3]
    caption3 = params[:caption3]
    title_img3 = params[:title_img3]
    published = params[:published]
    directory = "public/data"

    @event.title = title
    @event.date = date
    @event.content = content
    if published == "1"
      @event.published = true
    else
      @event.published = false
    end
    @image1 = @event.images[0]
    @image2 = @event.images[1]
    @image3 = @event.images[2]
    @event.save
    if @image1
      @image1.title = title_img1
      @image1.caption = caption1
      @image1.save
    end
    if @image2
      @image2.title = title_img2
      @image2.caption = caption2
      @image2.save
    end
    if @image3
      @image3.title = title_img3
      @image3.caption = caption3
      @image3.save
    end
    if image1
      if @image1
        @image1.deleteFile()
        @image1.destroy
      end
      hash = Time.new.to_formatted_s(:number) + "_" + rand(9999).to_s + File.extname(image1.original_filename)
      path = File.join(directory, hash)
      @image = @event.images.create(name: image1.original_filename, path: path, hashcode: hash, caption: caption1, title: title_img1)
      Image.uploadFile(image1,hash)
    end
    if image2
      if @image2
        @image2.deleteFile()
        @image2.destroy
      end
      hash = Time.new.to_formatted_s(:number) + "_" + rand(9999).to_s + File.extname(image2.original_filename)
      path = File.join(directory, hash)
      @image = @event.images.create(name: image2.original_filename, path: path, hashcode: hash, caption: caption2, title: title_img2)
      Image.uploadFile(image2,hash)
    end
    if image3
      if @image3
        @image3.deleteFile()
        @image3.destroy
      end
      hash = Time.new.to_formatted_s(:number) + "_" + rand(9999).to_s + File.extname(image3.original_filename)
      path = File.join(directory, hash)
      @image = @event.images.create(name: image3.original_filename, path: path, hashcode: hash, caption: caption3, title: title_img3)
      Image.uploadFile(image3,hash)
    end
    redirect_to(events_path, :notice => "Evento atualizado com sucesso!")
  end

  def edit
    @event = Event.find(params[:id])
    @languages = Language.all
  end

  def translate
    @event = Event.find(params[:id])
    @languages = Language.all
  end

  def destroy
    eventID = @event.id
    images = Image.where(:event_id => eventID)
    images.each do |image|
      image.deleteFile()
    end

    #Delete Translations
    translations = EventTranslation.where(event_id:@event.id)
    translations.each do |translation|
    	translation.destroy
    end

    @event.destroy
  end

  def index
   @events = Event.all
  end

  def show
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<% content_for :title, "Atualizar Evento" %>
<%= render :partial => "admin/header" %>
<div class="box">
  <%= render :partial => "admin/menu"  %>
  <div class="actions">
    <%= render :partial => "admin/eventsActions"  %>
  </div>
  <div id="eventID" style="display: none">
    <%= @event.id %>
  </div>
  <div class="view" id="addEvent">
    <div class="notifications"></div>

    <form action="/events/<%=@event.id%>" method="post" onsubmit="return validateEditEvent()" enctype="multipart/form-data">
      <label style="font-size: 23px;float: left;margin-top: 1px;"> Evento publicado: </label>
      <div class="flatRoundedCheckbox">
        <%if @event.published == true %>
            <input type="checkbox" value="1" id="flatOneRoundedCheckbox" checked name="published">
        <%else%>
            <input type="checkbox" value="1" id="flatOneRoundedCheckbox" name="published">
        <%end%>
        <label for="flatOneRoundedCheckbox"></label>
        <div></div>
      </div>
      <div id="translations">
       <select id="languagesSelect">
          <% @languages.each do |language| %>
          <option value="<%= language.code%>"><%= language.name %></option>
        <% end %>
        </select>        
      </div>
      <input type="text" name="title" id="titleVal" placeholder="Título" value="<%=@event.title%>" />
      <input type="text" class="translation" name="translatedTitle" id="translatedTitleVal" placeholder="Traducao do Título" value="" />
      <input type="text" name="date" id="dateVal" placeholder="Data" value="<%=@event.date%>"/>
      <textarea placeholder="Inserir texto" name="content" id="contentVal"><%=@event.content%></textarea><br/>
      <div><textarea class="translation" placeholder="Traduza aqui o texto" name="translatedContent" id="translatedContentVal"></textarea></div>
      <div class="imagesArea-new">
        <div class="image-div">
          <div class="left">
          <%if @event.images[0]%>
              <img src="/data/<%=@event.images[0].hashcode%>" alt="<%=@event.images[0].name%>" id="preview1" width="85" height="91">
          <%else%>
              <%=image_tag("default-avatar.png", alt: "default image", id: "preview1", width: 85, height: 91)%>
          <%end%>
          <input type="file" name="image1" class="upload custom-file-input" id="image1Val" />
          </div>
          <div class="right">
            <%if @event.images[0]%>
                <input type="text" name="title_img1" class="title_img" placeholder="Título da imagem" value="<%=@event.images[0].title%>" />
                <input type="text" class="translation" name="translatedTitle_img1" id="translatedTitleImg1Val" placeholder="Traducao do Título da imagem" value="" />
                <textarea rows="3" placeholder="Legenda" name="caption1" class="captionText" id="caption1Val"><%=@event.images[0].caption%></textarea>
                <textarea class="translation" placeholder="Traduza aqui a legenda da imagem" name="translatedCaption1" id="translatedCaption1Val"></textarea>
            <%else%>
                <input type="text" name="title_img1" class="title_img" placeholder="Título da imagem" />
                <textarea rows="3" placeholder="Legenda" name="caption1" class="captionText" id="caption1Val"></textarea>
            <%end%>
          </div>
        </div>
        <div class="image-div">
          <div class="left">
          <%if @event.images[1]%>
              <img src="/data/<%=@event.images[1].hashcode%>" alt="<%=@event.images[1].name%>" id="preview2" width="85" height="91">
          <%else%>
              <%=image_tag("default-avatar.png", alt: "default image", id: "preview2", width: 85, height: 91) %>
          <%end%>
          <input type="file" name="image2" class="upload custom-file-input" id="image2Val"/>
          </div>
        <div class="right">
          <%if @event.images[1]%>
              <input type="text" name="title_img2" class="title_img" placeholder="Título da imagem" value="<%=@event.images[1].title%>"/>
              <input type="text" class="translation" name="translatedTitle_img2" id="translatedTitleImg2Val" placeholder="Traducao do Título da imagem" value="" />
              <textarea rows="3" placeholder="Legenda" name="caption2" class="captionText" id="caption2Val"><%=@event.images[1].caption%></textarea>
              <textarea class="translation" placeholder="Traduza aqui a legenda da imagem" name="translatedCaption2" id="translatedCaption2Val"></textarea>
          <%else%>
              <input type="text" name="title_img2" class="title_img" placeholder="Título da imagem" />
              <textarea rows="3" placeholder="Legenda" name="caption2" class="captionText" id="caption2Val"></textarea>
          <%end%>
        </div>
        </div>
        <div class="image-div">
          <div class="left">
          <%if @event.images[2]%>
              <img src="/data/<%=@event.images[2].hashcode%>" alt="<%=@event.images[2].name%>" id="preview3" width="85" height="91">
          <%else%>
              <%=image_tag("default-avatar.png", alt: "default image", id: "preview3", width: 85, height: 91) %>
          <%end%>
          <input type="file" name="image3" class="upload custom-file-input" id="image3Val" />
        </div>
          <div class="right">
            <%if @event.images[2]%>
                <input type="text" name="title_img3" class="title_img" placeholder="Título da imagem" value="<%=@event.images[2].title%>"/>
                <input type="text" class="translation" name="translatedTitle_img3" id="translatedTitleImg3Val" placeholder="Traducao do Título da imagem" value="" />
                <textarea rows="3" placeholder="Legenda" name="caption3" class="captionText" id="caption3Val"><%=@event.images[2].caption%></textarea>
                <textarea class="translation" placeholder="Traduza aqui a legenda da imagem" name="translatedCaption3" id="translatedCaption3Val"></textarea>
            <%else%>
                <input type="text" name="title_img3" class="title_img" placeholder="Título da imagem"/>
                <textarea rows="3" placeholder="Legenda" name="caption3" class="captionText" id="caption3Val"></textarea>
            <%end%>
          </div>
        </div>
      </div>
      <input name="_method" type="hidden" value="patch" />
      <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
      <button class="redButton" id="addEventButton">Atualizar Evento</button>
    </form>

  </div>

</div>

app/views/events/index.html.erb
<% content_for :title, "Lista de Eventos" %>
<%= render :partial => "admin/header" %>
<div class="box">
  <%= render :partial => "admin/menu"  %>
  <div class="actions">
    <%= render :partial => "admin/eventsActions"  %>
  </div>


  <div class="view" id="listEvents">
    <div class="notifications">
      <% if flash[:notice] %>
          <div class="success"><%=flash[:notice]%></div>
      <% end %>
    </div>
    <% @events.each do |event|%>
    <div class="event" id="<%=event.id %>">
     <%=truncate(event.title, :length => 20) %>
      <div class="action">
        <button class="delete">Eliminar</button>
        <a href="<%= edit_event_path(event.id)%>"><button>Ver</button></a>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/events/new.html.erb
<% content_for :title, "Criar Evento" %>
<%= render :partial => "admin/header" %>
<div class="box">
  <%= render :partial => "admin/menu"  %>
  <div class="actions">
    <%= render :partial => "admin/eventsActions"  %>
  </div>

  <div class="view" id="addEvent">
    <div class="notifications"></div>

    <form action="/events" method="post" onsubmit="return validateAddEvent()" enctype="multipart/form-data">
      <input type="text" name="title" id="titleVal" placeholder="Título"/>
      <input type="text" name="date" id="dateVal" placeholder="Ano"/>
      <textarea rows="10" placeholder="Inserir texto" name="content" id="contentVal"></textarea><br/>
      <div class="imagesArea-new">
        <div class="image-div">
          <div class="left">
          <%=image_tag("default-avatar.png", alt: "default image", id: "preview1", width: 85, height: 91)%>
          <input type="file" name="image1" id="image1Val" class="upload custom-file-input"/>
          </div>
          <div class="right">
            <input type="text" name="title_img1" class="title_img" placeholder="Título da imagem" />
            <textarea rows="3" placeholder="Legenda" name="caption1" class="captionText" id="caption1Val"></textarea>
          </div>
        </div>
        <div class="image-div">
          <div class="left">
            <%=image_tag("default-avatar.png", alt: "default image", id: "preview2", width: 85, height: 91)%>
            <input type="file" name="image2" id="image2Val" class="upload custom-file-input"/>
          </div>
          <div class="right">
            <input type="text" name="title_img2" class="title_img" placeholder="Título da imagem" />
            <textarea rows="3" placeholder="Legenda" name="caption2" class="captionText" id="caption2Val"></textarea>
          </div>
        </div>
        <div class="image-div">
          <div class="left">
            <%=image_tag("default-avatar.png", alt: "default image", id: "preview3", width: 85, height: 91)%>
            <input type="file" name="image3" id="image3Val" class="upload custom-file-input"/>
          </div>
          <div class="right">
            <input type="text" name="title_img3" class="title_img" placeholder="Título da imagem" />
            <textarea rows="3" placeholder="Legenda" name="caption3" class="captionText" id="caption3Val"></textarea>
          </div>
        </div>
      </div>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
      <button class="redButton" id="addEventButton">Adicionar Evento</button>
    </form>

  </div>

</div>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/events/translate.html.erb
<% content_for :title, "Atualizar Evento" %>
<%= render :partial => "admin/header" %>
<div class="box">
  <%= render :partial => "admin/menu"  %>
  <div class="actions">
    <%= render :partial => "admin/eventsActions"  %>
    <li><a href="/translate">Traduzir</a></li>
  </div>

  <div class="view" id="addEvent">
    <div class="notifications"></div>
    <form action="/events/<%=@event.id%>" method="post" onsubmit="return validateEditEvent()" enctype="multipart/form-data">
      <select>
	<% @languages.each do |language| %>
	<option value="<%= language.code%>"><%= language.name %></option>
	<% end %>
      </select></br>
      <input type="text" name="title" id="titleVal" placeholder="Título" value="<%=@event.title%>" readonly />
      <input type="text" name="translatedTitle" id="translatedTitleVal" placeholder="Traducao do Título" value="" />
      <input type="text" name="date" id="dateVal" placeholder="Data" value="<%=@event.date%>" readonly/>
         
	 <textarea  rows="10" placeholder="Inserir texto" name="content" id="originalContentVal" readonly><%=@event.content%></textarea>
	 <textarea rows="10" placeholder="Traduza aqui o texto" name="translatedContent" id="translatedContentVal"></textarea></br>
      
      <input name="_method" type="hidden" value="patch" />
      <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
      <button class="redButton" id="translateEvent">Traduzir Evento</button>
    </form>

  </div>

</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>