config/routes.rb
Museusoaresreis::Application.routes.draw do

  # Authentication
  get "/login" => "admin#login", as: "login"
  get "/logout" => "admin#logout", as: "logout"
  get "/generatePassword" => "admin#generatePassword"

  # Administrator
  resources :administrators

  # Events
  resources :events
  get "/events/:id/translate" => "events#translate", as: "translate"


  # Languages
  resources :languages
  get "/getMissingLangs" => "languages#getMissingLangs"
  get "/changeLang" => "languages#changeLang"

  # Translations
  get "/findTranslation" => "event_translations#findTranslation"
  get "/updateTranslation" => "event_translations#updateTranslation"
  resources :event_translations

  # Root
  root "media#index"

  #Media
  get "/getDates" => "media#getDates"
  get "/getEvents" => "media#getEvents"
  get "/getTranslations" => "media#getTranslations"
  get "/getImage" => "media#getImage"
  get "/getEvent" => "media#getEvent"
  get "/puzzle" => "media#puzzle"
  get "/getEventTranslation" => "media#getTranslationEvent"

end

app/models/administrator.rb
require 'digest/sha1'
class Administrator < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 40 }
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 5 }
  before_create :encrypt_password

  def encrypt_password
    unless self.password.blank?
      self.password = Digest::SHA1.hexdigest(self.password.to_s)
    end
  end

  def self.authenticate(email,password)
    pwd = Digest::SHA1.hexdigest(password.to_s)
    Administrator.find_by_email_and_password(email,pwd)
  end
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
  before_action :find , :only => [:update, :destroy, :show]

  def find
    @administrator = Administrator.find(params[:id])
  end

  def index
    @administrator = Administrator.all
    respond_to do |format|
      format.html
      format.json{render :json => @administrator}
    end
  end

  def new
  end

  def update
    @administrator_alt = Administrator.find(params[:id])
    @administrator.update(:name => params[:name], :email => params[:email], :password => params[:password])
    respond_to do |format|
      format.html
      format.json{render :json => @administrator}
    end

  end

  def create
    @administrator = Administrator.create(:name => params['name'], :email => params['email'], :password => params['password'])
    respond_to do |format|
      format.html
      format.json{render :json => @administrator}
    end
  end

  def destroy
    @administrator.destroy
  end

  def show
    respond_to do |format|
      format.html
      format.json{render :json => @administrator}
    end
  end
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  require 'digest/sha1'
  before_action :find , :only => [:update, :destroy, :show, :edit]
  before_action :check_auth, :only => [:new, :create, :update, :edit, :destroy, :index, :show]

  def find
    @administrator = Administrator.find(params[:id])
  end

  def new
  end

  def create
    name = params[:name]
    email = params[:email]
    password = params[:password]
    if(Administrator.where(email: email).empty?)
      @administrator = Administrator.create(:name => name, :email => email, :password => password)
      @result = @administrator
    else
      @result = ["emailExists"]
    end
    respond_to do |format|
      format.json{render :json => @result}
    end
  end

  def update
    @administrator = Administrator.find(params[:id])
    if(Administrator.where(email: params[:email]).where.not(id: params[:id]).empty?)
      @administrator.name = params[:name]
      @administrator.email = params[:email]
      if(!params[:password].empty?)
        @administrator.password = Digest::SHA1.hexdigest(params[:password].to_s)
      end
      @administrator.save
      @result = @administrator
    else
      @result = ["emailExists"]
    end
      respond_to do |format|
      format.json{render :json => @result}
    end
  end

  def edit

  end

  def destroy
    @administrator.destroy
  end

  def index
    @administrator = Administrator.all
    respond_to do |format|
      format.html
      format.json{render :json => @administrator}
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json{render :json => @administrator}
    end
  end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/create.html.erb
<h1>Administrators#create</h1>
<p>Find me in app/views/administrators/create.html.erb</p>

app/views/administrators/destroy.html.erb
<h1>Administrators#destroy</h1>
<p>Find me in app/views/administrators/destroy.html.erb</p>

app/views/administrators/edit.html.erb
<% content_for :title, "Atualizar Administrador" %>
<%= render :partial => "admin/header" %>
<div class="box">
  <%= render :partial => "admin/menu"  %>
  <div class="actions">
    <%= render :partial => "admin/adminActions"  %>
  </div>
  <div class="view" id="editAdmin">

    <div class="notifications">
    </div>
    <input type="text" id="nameVal" placeholder="Nome" value="<%=@administrator.name%>"/><br/>
    <input type="email" id="emailVal" placeholder="Email" value="<%=@administrator.email%>"/><br/>
    <input type="password" id="password1Val" placeholder="Nova password"/><br/>
    <input type="password" id="password2Val" placeholder="Confirme a password"/><br/>

    <button class="redButton" id="updateAdminButton" admin="<%=@administrator.id%>">Atualizar Administrador</button>
  </div>
</div>

app/views/administrators/index.html.erb
<% content_for :title, "Adicionar Administrador" %>
<%= render :partial => "admin/header" %>
<div class="box">
  <%= render :partial => "admin/menu"  %>
  <div class="actions">
    <%= render :partial => "admin/adminActions"  %>
  </div>
  <div class="view" id="listAdmins">

    <% @administrator.each do |admin|%>
        <div class="admin" id="<%=admin.id %>">
          <div class="name"><%=admin.name %></div>
          <div class="action">
            <button class="delete">Eliminar</button>
            <a href="<%= edit_administrator_path(admin.id)%>"><button>Ver</button></a>
          </div>
        </div>
    <% end %>

  </div>
</div>

app/views/administrators/new.html.erb
<% content_for :title, "Adicionar Administrador" %>
<%= render :partial => "admin/header" %>
<div class="box">
  <%= render :partial => "admin/menu"  %>
  <div class="actions">
    <%= render :partial => "admin/adminActions"  %>
  </div>
  <div class="view" id="addAdmin">

    <div class="notifications">
    </div>
    <input type="text" id="nameVal" placeholder="Nome"/><br/>
    <input type="email" id="emailVal" placeholder="Email"/><br/>
    <input type="password" id="password1Val" placeholder="Password"/><br/>
    <input type="password" id="password2Val" placeholder="Confirme a password"/><br/>

    <button class="redButton" id="addAdminButton">Adicionar Administrador</button>
  </div>
</div>

app/views/administrators/show.html.erb
<h1>Administrators#show</h1>
<p>Find me in app/views/administrators/show.html.erb</p>

app/views/administrators/update.html.erb
<h1>Administrators#update</h1>
<p>Find me in app/views/administrators/update.html.erb</p>